/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DjemalsRouteImport } from './routes/djemals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DjemalsIndexRouteImport } from './routes/djemals.index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as DjemalsPostsRouteImport } from './routes/djemals.posts'
import { Route as DjemalsCommentsRouteImport } from './routes/djemals.comments'
import { Route as DjemalsCategoriesRouteImport } from './routes/djemals.categories'
import { Route as DjemalsApiDocsRouteImport } from './routes/djemals.api-docs'
import { Route as DjemalsAboutRouteImport } from './routes/djemals.about'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DjemalsPostsIndexRouteImport } from './routes/djemals.posts.index'
import { Route as DjemalsPostsNewRouteImport } from './routes/djemals.posts.new'
import { Route as DjemalsPostsIdRouteImport } from './routes/djemals.posts.$id'
import { Route as ApiPublicPostsRouteImport } from './routes/api/public/posts'
import { Route as ApiPublicImagesRouteImport } from './routes/api/public/images'
import { Route as ApiPublicCommentsRouteImport } from './routes/api/public/comments'
import { Route as ApiPublicImagesKeyRouteImport } from './routes/api/public/images.$key'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DjemalsRoute = DjemalsRouteImport.update({
  id: '/djemals',
  path: '/djemals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DjemalsIndexRoute = DjemalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DjemalsRoute,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DjemalsPostsRoute = DjemalsPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DjemalsRoute,
} as any)
const DjemalsCommentsRoute = DjemalsCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DjemalsRoute,
} as any)
const DjemalsCategoriesRoute = DjemalsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DjemalsRoute,
} as any)
const DjemalsApiDocsRoute = DjemalsApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => DjemalsRoute,
} as any)
const DjemalsAboutRoute = DjemalsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DjemalsRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DjemalsPostsIndexRoute = DjemalsPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DjemalsPostsRoute,
} as any)
const DjemalsPostsNewRoute = DjemalsPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DjemalsPostsRoute,
} as any)
const DjemalsPostsIdRoute = DjemalsPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DjemalsPostsRoute,
} as any)
const ApiPublicPostsRoute = ApiPublicPostsRouteImport.update({
  id: '/api/public/posts',
  path: '/api/public/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImagesRoute = ApiPublicImagesRouteImport.update({
  id: '/api/public/images',
  path: '/api/public/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommentsRoute = ApiPublicCommentsRouteImport.update({
  id: '/api/public/comments',
  path: '/api/public/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImagesKeyRoute = ApiPublicImagesKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiPublicImagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/djemals': typeof DjemalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/djemals/about': typeof DjemalsAboutRoute
  '/djemals/api-docs': typeof DjemalsApiDocsRoute
  '/djemals/categories': typeof DjemalsCategoriesRoute
  '/djemals/comments': typeof DjemalsCommentsRoute
  '/djemals/posts': typeof DjemalsPostsRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/djemals/': typeof DjemalsIndexRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/images': typeof ApiPublicImagesRouteWithChildren
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/djemals/posts/$id': typeof DjemalsPostsIdRoute
  '/djemals/posts/new': typeof DjemalsPostsNewRoute
  '/djemals/posts/': typeof DjemalsPostsIndexRoute
  '/api/public/images/$key': typeof ApiPublicImagesKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/djemals/about': typeof DjemalsAboutRoute
  '/djemals/api-docs': typeof DjemalsApiDocsRoute
  '/djemals/categories': typeof DjemalsCategoriesRoute
  '/djemals/comments': typeof DjemalsCommentsRoute
  '/post/$slug': typeof PostSlugRoute
  '/djemals': typeof DjemalsIndexRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/images': typeof ApiPublicImagesRouteWithChildren
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/djemals/posts/$id': typeof DjemalsPostsIdRoute
  '/djemals/posts/new': typeof DjemalsPostsNewRoute
  '/djemals/posts': typeof DjemalsPostsIndexRoute
  '/api/public/images/$key': typeof ApiPublicImagesKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/djemals': typeof DjemalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/category/$slug': typeof CategorySlugRoute
  '/djemals/about': typeof DjemalsAboutRoute
  '/djemals/api-docs': typeof DjemalsApiDocsRoute
  '/djemals/categories': typeof DjemalsCategoriesRoute
  '/djemals/comments': typeof DjemalsCommentsRoute
  '/djemals/posts': typeof DjemalsPostsRouteWithChildren
  '/post/$slug': typeof PostSlugRoute
  '/djemals/': typeof DjemalsIndexRoute
  '/api/public/comments': typeof ApiPublicCommentsRoute
  '/api/public/images': typeof ApiPublicImagesRouteWithChildren
  '/api/public/posts': typeof ApiPublicPostsRoute
  '/djemals/posts/$id': typeof DjemalsPostsIdRoute
  '/djemals/posts/new': typeof DjemalsPostsNewRoute
  '/djemals/posts/': typeof DjemalsPostsIndexRoute
  '/api/public/images/$key': typeof ApiPublicImagesKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/djemals'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/djemals/about'
    | '/djemals/api-docs'
    | '/djemals/categories'
    | '/djemals/comments'
    | '/djemals/posts'
    | '/post/$slug'
    | '/djemals/'
    | '/api/public/comments'
    | '/api/public/images'
    | '/api/public/posts'
    | '/djemals/posts/$id'
    | '/djemals/posts/new'
    | '/djemals/posts/'
    | '/api/public/images/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/djemals/about'
    | '/djemals/api-docs'
    | '/djemals/categories'
    | '/djemals/comments'
    | '/post/$slug'
    | '/djemals'
    | '/api/public/comments'
    | '/api/public/images'
    | '/api/public/posts'
    | '/djemals/posts/$id'
    | '/djemals/posts/new'
    | '/djemals/posts'
    | '/api/public/images/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/djemals'
    | '/sitemap.xml'
    | '/category/$slug'
    | '/djemals/about'
    | '/djemals/api-docs'
    | '/djemals/categories'
    | '/djemals/comments'
    | '/djemals/posts'
    | '/post/$slug'
    | '/djemals/'
    | '/api/public/comments'
    | '/api/public/images'
    | '/api/public/posts'
    | '/djemals/posts/$id'
    | '/djemals/posts/new'
    | '/djemals/posts/'
    | '/api/public/images/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DjemalsRoute: typeof DjemalsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PostSlugRoute: typeof PostSlugRoute
  ApiPublicCommentsRoute: typeof ApiPublicCommentsRoute
  ApiPublicImagesRoute: typeof ApiPublicImagesRouteWithChildren
  ApiPublicPostsRoute: typeof ApiPublicPostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/djemals': {
      id: '/djemals'
      path: '/djemals'
      fullPath: '/djemals'
      preLoaderRoute: typeof DjemalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/djemals/': {
      id: '/djemals/'
      path: '/'
      fullPath: '/djemals/'
      preLoaderRoute: typeof DjemalsIndexRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/djemals/posts': {
      id: '/djemals/posts'
      path: '/posts'
      fullPath: '/djemals/posts'
      preLoaderRoute: typeof DjemalsPostsRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/djemals/comments': {
      id: '/djemals/comments'
      path: '/comments'
      fullPath: '/djemals/comments'
      preLoaderRoute: typeof DjemalsCommentsRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/djemals/categories': {
      id: '/djemals/categories'
      path: '/categories'
      fullPath: '/djemals/categories'
      preLoaderRoute: typeof DjemalsCategoriesRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/djemals/api-docs': {
      id: '/djemals/api-docs'
      path: '/api-docs'
      fullPath: '/djemals/api-docs'
      preLoaderRoute: typeof DjemalsApiDocsRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/djemals/about': {
      id: '/djemals/about'
      path: '/about'
      fullPath: '/djemals/about'
      preLoaderRoute: typeof DjemalsAboutRouteImport
      parentRoute: typeof DjemalsRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/djemals/posts/': {
      id: '/djemals/posts/'
      path: '/'
      fullPath: '/djemals/posts/'
      preLoaderRoute: typeof DjemalsPostsIndexRouteImport
      parentRoute: typeof DjemalsPostsRoute
    }
    '/djemals/posts/new': {
      id: '/djemals/posts/new'
      path: '/new'
      fullPath: '/djemals/posts/new'
      preLoaderRoute: typeof DjemalsPostsNewRouteImport
      parentRoute: typeof DjemalsPostsRoute
    }
    '/djemals/posts/$id': {
      id: '/djemals/posts/$id'
      path: '/$id'
      fullPath: '/djemals/posts/$id'
      preLoaderRoute: typeof DjemalsPostsIdRouteImport
      parentRoute: typeof DjemalsPostsRoute
    }
    '/api/public/posts': {
      id: '/api/public/posts'
      path: '/api/public/posts'
      fullPath: '/api/public/posts'
      preLoaderRoute: typeof ApiPublicPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/images': {
      id: '/api/public/images'
      path: '/api/public/images'
      fullPath: '/api/public/images'
      preLoaderRoute: typeof ApiPublicImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comments': {
      id: '/api/public/comments'
      path: '/api/public/comments'
      fullPath: '/api/public/comments'
      preLoaderRoute: typeof ApiPublicCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/images/$key': {
      id: '/api/public/images/$key'
      path: '/$key'
      fullPath: '/api/public/images/$key'
      preLoaderRoute: typeof ApiPublicImagesKeyRouteImport
      parentRoute: typeof ApiPublicImagesRoute
    }
  }
}

interface DjemalsPostsRouteChildren {
  DjemalsPostsIdRoute: typeof DjemalsPostsIdRoute
  DjemalsPostsNewRoute: typeof DjemalsPostsNewRoute
  DjemalsPostsIndexRoute: typeof DjemalsPostsIndexRoute
}

const DjemalsPostsRouteChildren: DjemalsPostsRouteChildren = {
  DjemalsPostsIdRoute: DjemalsPostsIdRoute,
  DjemalsPostsNewRoute: DjemalsPostsNewRoute,
  DjemalsPostsIndexRoute: DjemalsPostsIndexRoute,
}

const DjemalsPostsRouteWithChildren = DjemalsPostsRoute._addFileChildren(
  DjemalsPostsRouteChildren,
)

interface DjemalsRouteChildren {
  DjemalsAboutRoute: typeof DjemalsAboutRoute
  DjemalsApiDocsRoute: typeof DjemalsApiDocsRoute
  DjemalsCategoriesRoute: typeof DjemalsCategoriesRoute
  DjemalsCommentsRoute: typeof DjemalsCommentsRoute
  DjemalsPostsRoute: typeof DjemalsPostsRouteWithChildren
  DjemalsIndexRoute: typeof DjemalsIndexRoute
}

const DjemalsRouteChildren: DjemalsRouteChildren = {
  DjemalsAboutRoute: DjemalsAboutRoute,
  DjemalsApiDocsRoute: DjemalsApiDocsRoute,
  DjemalsCategoriesRoute: DjemalsCategoriesRoute,
  DjemalsCommentsRoute: DjemalsCommentsRoute,
  DjemalsPostsRoute: DjemalsPostsRouteWithChildren,
  DjemalsIndexRoute: DjemalsIndexRoute,
}

const DjemalsRouteWithChildren =
  DjemalsRoute._addFileChildren(DjemalsRouteChildren)

interface ApiPublicImagesRouteChildren {
  ApiPublicImagesKeyRoute: typeof ApiPublicImagesKeyRoute
}

const ApiPublicImagesRouteChildren: ApiPublicImagesRouteChildren = {
  ApiPublicImagesKeyRoute: ApiPublicImagesKeyRoute,
}

const ApiPublicImagesRouteWithChildren = ApiPublicImagesRoute._addFileChildren(
  ApiPublicImagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DjemalsRoute: DjemalsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategorySlugRoute: CategorySlugRoute,
  PostSlugRoute: PostSlugRoute,
  ApiPublicCommentsRoute: ApiPublicCommentsRoute,
  ApiPublicImagesRoute: ApiPublicImagesRouteWithChildren,
  ApiPublicPostsRoute: ApiPublicPostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
